Repository SPiN-Lab/connPFM, pull requests merged in 2021-12, with the labels that each got.

#41 [ENH] Add different thresholding options to connectivity analysis
  connPFM/__init__.py
  connPFM/cli/connPFM.py
  connPFM/connPFM.py
  connPFM/connectivity/__init__.py
  connPFM/connectivity/connectivity_utils.py
  connPFM/connectivity/ev.py
  connPFM/debiasing/__init__.py
  connPFM/deconvolution/__init__.py
  connPFM/tests/__init__.py
  connPFM/tests/conftest.py
  connPFM/tests/test_debiasing.py
  connPFM/tests/test_ev.py
  connPFM/tests/test_integration.py
  ismrm2022/stability_pfm.py
Labels: enhancement, impact: high, priority: high

#39 Deb output
  connPFM/cli/connPFM.py
  connPFM/connPFM.py
  connPFM/debiasing/debiasing.py
  connPFM/tests/test_integration.py
Labels: enhancement, effort: low

#43 Build docker with current brach for both PRs and main branches
  .circleci/config.yml
  docker_slim/Dockerfile
Labels: testing

#45 correct the path to compute_slars.py inside the image
  connPFM/deconvolution/compute_slars.sh
  connPFM/tests/test_integration.py
  docker_slim/Dockerfile
Labels: bug

#44 Add matrix argument as an output string for ev_workflow
  connPFM/connPFM.py
  connPFM/connectivity/ev.py
  connPFM/tests/test_integration.py
Labels: enhancement

#47 Output rss and peak timepoints as txt
  connPFM/cli/connPFM.py
  connPFM/connPFM.py
  connPFM/connectivity/ev.py
  connPFM/tests/conftest.py
  connPFM/tests/test_integration.py
Labels: enhancement

#48 Extend testing to different versions of Python with matrix configuration
  .circleci/config.yml
Labels: testing
