Repository SPiN-Lab/connPFM, pull requests merged in 2022-03, with the labels that each got.

#67 Add io file for reading a saving files, and support multi-echo
  connPFM/cli/connPFM.py
  connPFM/connPFM.py
  connPFM/connectivity/ev.py
  connPFM/debiasing/debiasing.py
  connPFM/deconvolution/roiPFM.py
  connPFM/tests/test_ev.py
  connPFM/tests/test_integration.py
  connPFM/tests/test_utils.py
  connPFM/utils/io.py
  connPFM/utils/surrogate_generator.py
Labels: refactoring

#72 Move connPFM_slim container to OSF
  connPFM/deconvolution/compute_slars.sh
  connPFM/deconvolution/roiPFM.py
  connPFM/deconvolution/stability_lars_caller.py
Labels: refactoring

#73 Eliminate docker image and tests
  .circleci/config.yml
  docker_slim/Dockerfile
Labels: impact: low, testing

#77 HRF is defined as `nscans` divided by number of echos
  connPFM/deconvolution/roiPFM.py
  connPFM/deconvolution/stability_lars.py
  connPFM/deconvolution/stability_lars_caller.py
Labels: bug

#78 Make the conversion to integrer before multipying by the nTE
  connPFM/deconvolution/stability_lars.py
Labels: bug

#80 Correct HRF shape in debias and output names for multiecho
  .circleci/config.yml
  connPFM/debiasing/debiasing.py
  connPFM/debiasing/debiasing_functions.py
Labels: bug
